[project]
name = "throw"
version = "0.1.0"
repo = "nibble-dev/throw"
description = "Create errors and throw them easily"
language = "c"


[nibbles]



[build]
srcs = ["src/throw.h"]
cflags = []
libs = []
include_dirs = ["nibs"]
